#Demo Spring application

trigger:
 branches:
    include:
      - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Aathis Devops Junit Stage-1'
    condition: always()
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Aathis Devops Running unit test demo'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              options: '--no-transfer-progress'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true
              
  - stage: 'BuildArtifact'
    displayName: 'Aathis Devops Building Artifact Stage -2'
    condition: and(succeeded(),ne(variables['Build.Reason'],'PullRequest')) 
    dependsOn: 'Junit'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Aathis Devops Building Artifact Job 2'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            options: '--no-transfer-progress'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false