# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'junit'
    displayName: 'Stage Aathi Junit Test Trial'
    jobs:
      - job: 'junit'
        displayName: 'Job Name Aathi Junit Test trial'
        steps:
          - script: echo 'Running Aathi test trial'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              options: '--no-transfer-progress'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true


  - stage: 'BuildArtifact'
    displayName: 'Stage 2 Aathi Artifacts'
    jobs:
      - job: 'BuildArtifact'
        displayName: 'Job 2 Aathi Artifacts'
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            options: '--no-transfer-progress'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
